index:
    path: /
    controller: App\Controller\DefaultController::index

login:
    path: /login
    controller: App\Controller\DefaultController::login

user:
  path: /user
  controller: App\Controller\DefaultController::getName